spring.application.name=service-discovery
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=4090
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:${server.port}/eureka/

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always