spring.application.name=ai-service
server.port=4050
spring.mongodb.uri=${AI_SERVICE_MONGO_URI}
spring.mongodb.database=ai-service
eureka.client.service-url.defaultZone=http://localhost:4090/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
