server.port=4000

# --- Workout Service Routes ---
spring.cloud.gateway.server.webmvc.routes[0].id=workout-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://workout-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/workout/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=2

# --- Sleep Service Routes ---
spring.cloud.gateway.server.webmvc.routes[1].id=sleep-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://sleep-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/sleep/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=2

# --- Nutrition Service Routes ---
spring.cloud.gateway.server.webmvc.routes[2].id=nutrition-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://nutrition-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/nutrition/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=2

# --- Supplement Service Routes ---
spring.cloud.gateway.server.webmvc.routes[3].id=supplement-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://supplement-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/supplement/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=2

# --- AI Service Routes ---
spring.cloud.gateway.server.webmvc.routes[4].id=ai-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ai-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/ai/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=2
