server.port=4030
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${NT_SERVICE_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
