spring.application.name=config-server
server.port=4080

# Use filesystem (classpath) for config storage
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations

# Register with Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:4090/eureka}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
